#!/bin/bash
# script untuk menginstal PKSFZ

#+------------------------------------------+
#| Program : Pemecah kata sandi file ZIP    |
#| Pembuat : Rofi [FII14]                   |  
#| Github  : https://github.com/FII14/PKSFZ |
#+------------------------------------------+
#| COPYRIGHT (C) 2023 FII14                 |
#+------------------------------------------+

if [[ $EUID != 0 ]]; then
    echo "Silahkan jalankan sebagai root."
    exit 1
    
else
    chmod +x pksfz
    mv pksfz /usr/bin
    echo "PKSFZ berhasil diinstal."
    sleep 3
    echo "Untuk menjalankannya ketikkan perintah 'pksfz'."
fi
