#!/usr/bin/env python3

import zipfile
import os

while True:
    # Meminta input nama file ZIP
    zip_filename = input("Masukkan nama file ZIP: ")

    # Memeriksa apakah file ZIP ada
    if not os.path.isfile(zip_filename):
        print("File ZIP tidak ditemukan.")
    else:
        break

while True:
    # Meminta input nama file wordlist
    wordlist_file = input("Masukkan nama file wordlist: ")

    # Memeriksa apakah file wordlist ada
    if not os.path.isfile(wordlist_file):
        print("File wordlist tidak ditemukan.")
    else:
        break

# Membaca file wordlist dan mencoba kata sandi
with open(wordlist_file, 'r') as wordlist:
    password_found = False
    for password in wordlist:
        password = password.strip()
        try:
            with zipfile.ZipFile(zip_filename, 'r') as zip_file:
                zip_file.extractall(pwd=password.encode())
                print(f"\nKata sandi ditemukan: {password}")
                password_found = True
                break
        except Exception:
            pass

    if not password_found:
        print("Kata sandi tidak ditemukan dalam wordlist.")